language: swift

branches:
  only:
    - master

xcode_project: Tactile.xcodeproj
xcode_scheme: TactileTests
osx_image: xcode11.2

script:
  - xcodebuild test -project Tactile.xcodeproj -scheme TactileTests -destination "platform=iOS Simulator,name=iPhone 11"
